# Generated by Django 4.2.7 on 2024-03-04 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='username',
            new_name='user_id',
        ),
    ]
